<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   id="Layer_29"
   data-name="Layer 29"
   viewBox="0 0 256 256"
   version="1.1"
   sodipodi:docname="makefile.svg"
   inkscape:version="1.0beta2 (2b71d25, 2019-12-03)">
  <metadata
     id="metadata852">
    <rdf:RDF>
      <cc:Work
         rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title>java_v2</dc:title>
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <sodipodi:namedview
     pagecolor="#ffffff"
     bordercolor="#666666"
     inkscape:document-rotation="0"
     borderopacity="1"
     objecttolerance="10"
     gridtolerance="10"
     guidetolerance="10"
     inkscape:pageopacity="0"
     inkscape:pageshadow="2"
     inkscape:window-width="1484"
     inkscape:window-height="809"
     id="namedview850"
     showgrid="false"
     inkscape:zoom="2.3476562"
     inkscape:cx="128"
     inkscape:cy="128"
     inkscape:window-x="81"
     inkscape:window-y="103"
     inkscape:window-maximized="0"
     inkscape:current-layer="Layer_29" />
  <defs
     id="defs835">
    <style
       id="style833">.cls-1{fill:#d42327;}.cls-2{fill:#fff;}</style>
  </defs>
  <title
     id="title837">java_v2</title>
  <rect
     class="cls-1"
     width="256"
     height="256"
     id="rect839"
     style="fill:#000000;fill-opacity:1" />
  <text
     xml:space="preserve"
     style="font-style:normal;font-variant:normal;font-weight:bold;font-stretch:normal;font-size:74.3317px;line-height:1.25;font-family:sans-serif;-inkscape-font-specification:'sans-serif Bold';font-variant-ligatures:normal;font-variant-caps:normal;font-variant-numeric:normal;font-variant-east-asian:normal;fill:#ffffff;stroke-width:2.32287"
     x="50.665157"
     y="133.50806"
     id="text856"
     transform="scale(0.82291239,1.2151962)"><tspan
       sodipodi:role="line"
       id="tspan854"
       x="50.665157"
       y="133.50806"
       style="font-style:normal;font-variant:normal;font-weight:bold;font-stretch:normal;font-size:74.3317px;font-family:sans-serif;-inkscape-font-specification:'sans-serif Bold';font-variant-ligatures:normal;font-variant-caps:normal;font-variant-numeric:normal;font-variant-east-asian:normal;fill:#ffffff;stroke-width:2.32287">Make</tspan></text>
</svg>
