FROM nginx:1.14.1

# Get dependancies for node install
RUN apt-get update \
 && apt-get install -y -q --no-install-recommends \
    ca-certificates curl gnupg gnupg2 gnupg1 nano git bzip2 libfontconfig1-dev xz-utils \
    wget \
 && apt-get clean \
 && rm -r /var/lib/apt/lists/*
WORKDIR /app
# Install Node
ENV NPM_CONFIG_LOGLEVEL info
ENV NODE_VERSION 8.15.0

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get install -y nodejs
RUN npm install gulp -g && \
    npm install -g gulp-cli && \
    npm install -g jspm && \
    npm install aurelia-cli -g

COPY install_dependencies.sh /app
RUN chmod +x /app/install_dependencies.sh
#RUN /app/install_dependencies.sh

COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh
ENTRYPOINT ["/app/entrypoint.sh"]
